name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy_vercel:
    needs: build
    runs-on: ubuntu-latest
    # Run this job only when the VERCEL_TOKEN and VERCEL_PROJECT_ID secrets are set in the repository
    if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_PROJECT_ID != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # Using Vercel CLI to deploy the built `dist` folder. Requires VERCEL_TOKEN and VERCEL_PROJECT_ID secrets.
          npx vercel deploy --prod --confirm --token "$VERCEL_TOKEN" --project-id "${{ secrets.VERCEL_PROJECT_ID }}"

  deploy_netlify:
    needs: build
    runs-on: ubuntu-latest
    # Run this job only when the Netlify auth token and site id are provided
    if: ${{ secrets.NETLIFY_AUTH_TOKEN != '' && secrets.NETLIFY_SITE_ID != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Netlify CLI
        run: npm ci && npm install -g netlify-cli
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          # Deploying the `dist` directory using Netlify CLI. Requires NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID.
          netlify deploy --dir=dist --site="${{ secrets.NETLIFY_SITE_ID }}" --prod --auth "$NETLIFY_AUTH_TOKEN"
